spring:
  application:
    name: Userer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/DB_USER
    username: lucas
    password: 123
    driver-class-name: org.postgresql.Driver

