spring:
  application:
    name: Storage
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5434/DB_STORAGE
    username: lucas
    password: 123
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    addresses: gorilla.lmq.cloudamqp.com
    username: iophmrpo
    password: lB8PghYkZs684IJHQYKQFprFe5hm6jTv
    virtual-host: iophmrpo
server:
  port: 8084